apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: a
spec:
  containers:
    - name: api-pod-worker
      image: rjacdevops/api-service-test:latest
      ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: b
spec:
  selector:
    app: a
  ports:
    - port: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-route
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: b
            port:
              number: 8081