apiVersion: v1
kind: Service
metadata:
  name: prometheus-endpoint
  labels:
    app: prometheus-endpoint
spec:
  selector:
    prometheus: prometheus
  ports:
  - port: 9090
    targetPort: web
    name: web
  sessionAffinity: ClientIP
 