apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: triton-monitor
  labels:
    app: triton-monitor
spec:
  endpoints:
  - interval: 30s
    port: metrics-triton
  selector:
    matchLabels:
      app: triton-endpoint
  namespaceSelector:
    matchNames:
    - inference