apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-pod
  template:
    metadata:
      labels:
        app: client-pod
    spec:
      containers:
        - name: client-container
          image: rjacdevops/mb_overall_client:latest
          ports:
            - containerPort: 8000
          env:
            - name: ICD_ENDPOINT
              value: "http://classification-endpoint:8081"
            - name: NER_ENDPOINT
              value: "http://ner-endpoint:8081"
          resources:
            requests:
              memory: "0.25Gi"
              cpu: "0.15"
            limits:
              memory: "4Gi"
              cpu: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: client-endpoint
spec:
  selector:
    app: client-pod
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer