apiVersion: v1
kind: Secret
metadata:
  name:  aws-credentials
type: Opaque
data:
  AWS_DEFAULT_REGION: <echo -n AWS_DEFAULT_REGION | base64>
  AWS_ACCESS_KEY_ID: <echo -n AWS_ACCESS_KEY_ID | base64>
  AWS_SECRET_ACCESS_KEY: <echo -n AWS_SECRET_ACCESS_KEY | base64>