apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
        - name: triton-container
          image: nvcr.io/nvidia/tritonserver:22.10-py3
          args: ['tritonserver', '--model-repository=s3://nlp-medical-biller-group-datasets-mlo4/models']
          ports:
            - containerPort: 8000
              name: http-triton
            - containerPort: 8001
              name: grpc-triton
            - containerPort: 8002
              name: metrics-triton
          env:
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_DEFAULT_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: TRITON_MODEL_REPOSITORY
              value: "s3://nlp-medical-biller-group-datasets-mlo4/models"
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "6Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: triton-endpoint
  labels:
    app: triton-endpoint
spec:
  selector:
    app: triton
  ports:
    - port: 8000
      name: http-triton
    - port: 8001
      name: grpc-triton
    - port: 8002
      name: metrics-triton
